export enum ActivityArea {CALL_CENTERS='CALL_CENTERS',TRAINING ='TRAINING' ,HUMAN_RESSOURCES = 'HUMAN_RESSOURCES',
 ENGINEERING ='ENGINEERING',MARKETING='MARKETING',COMPUTER_SCIENCE ='COMPUTER_SCIENCE' ,
 TELECOMMUNICATIONS = 'TELECOMMUNICATIONS',INDUSTRY ='INDUSTRY',INFORMATION_TECHNOLOGY='INFORMATION_TECHNOLOGY',
 TRADE ='TRADE' ,SALE = 'SALE',TRANSPORTATION ='TRANSPORTATION',SCIENCE='SCIENCE',RESEARCH ='RESEARCH',
 REAL_ESTATE = 'REAL_ESTATE',QUALITY_CONTROL ='QUALITY_CONTROL',PURCHASING_PROCUEMENT='PURCHASING_PROCUEMENT',
 RESPHARMACEUTICALSEARCH ='PHARMACEUTICALS' ,CLIENT_SERVICES = 'CLIENT_SERVICES',Media_JOURNALISM ='Media_JOURNALISM',
 MANAGEMENT='MANAGEMENT',LEGAL ='LEGAL' ,INSURANCE = 'INSURANCE',INSTALLATION_MAINTENANCE_REPAIR ='INSTALLATION_MAINTENANCE_REPAIR',
 HEALTH='HEALTH',DESIGN ='DESIGN'}